### PR TITLE
Email validation

### LINKED ISSUE #17: (Auth) Email format validation.
The Signup and Login forms should validate the email input

### PR DESCRIPTION
**Pull request by DamarisTorrent**

### CODE REVIEW

**Comment by bmc1995** [comment]
Looks good to me, I like the helper text! I plan to eventually implement [zod](https://zod.dev/) for all form validation, but that's outside the scope of this issue.

Zod example:
```typescript
export const loginFormSchema = z
  .object({
    email: z
      .string({ required_error: "Email is required." })
      .email({ message: "Invalid email address." })
      .max(100)
      .trim()
    password: z
      .string({ required_error: "Password is required.", coerce: true })
      .trim()
      .regex(/\s/, "Invalid Password.")
      .min(8, "Invalid Password."),
  })
  .strict()
  .required();
```

**Comment by DamarisTorrent** [comment]
I just recently started using zod at work for the first time, if you have any questions let me know!

**Comment by bmc1995** [comment]
@DamarisTorrent 
Awesome!!  Thanks :)

**Comment by bmc1995** [comment]
> I just recently started using zod at work for the first time, if you have any questions let me know!

Hey @DamarisTorrent,
For zod schemas which could be common in multiple places, would you rather `.pick` from a zod object - or - define schemas separately, combining them into an object as needed for each use?  I've given a little thought towards defining them all separately and wanted your input if you have the time.  Thanks!

**Pull request merged**
